
spring:
  application:
    name: api-gateway-zuul


server:
  port: 8765


eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka;

zuul:
  routes:
    productCatalog:
      serviceId: product-catalog-service
      path: /productc/**